from fastapi import APIRouter,Depends
from langchain_core.messages import HumanMessage

from routes.auth import get_current_user
from database import get_database
from models.chat import ChatMessage,Chats
from services.chat_service import chat_with_bot
from utils.memory_history import MemoryHistory
from schemas.chat import chat_entity,chat_schema

from uuid import uuid4
from datetime import datetime

import logging
logger = logging.getLogger(__name__)


app = APIRouter(prefix='/chat',tags=['Chat'])


# Create chat
@app.post("/")
async def create_chat(user = Depends(get_current_user)):
    chat = Chats(
        user_id=user['user_id'],
        chat_id=str(uuid4()),
        chat_title='hehe',
        created_at=datetime.utcnow()
    )
    
    db = await get_database()
    
    await db.chats.insert_one(chat_entity(chat.model_dump()))
    logger.info("Chat Created - chat id ")
    return {"message": "Chat created", "chat_id": chat.chat_id}



# list chat
# Add this to your routes/chat.py — replace your existing /chat/list endpoint
# chats
@app.get("/list")
async def list_chats(user=Depends(get_current_user)):
    db = await get_database()
    
    # Get all chats for this user, newest first
    cursor = db.chats.find(
        {"user_id": user["user_id"]}
    ).sort("created_at", -1)  # -1 = descending = newest first
    
    chats = await cursor.to_list(length=50)
    
    result = []
    for chat in chats:
        # Get the first user message to use as the chat title
        first_msg = await db.chat_messages.find_one(
            {"chat_id": chat["chat_id"], "role": "user"},
            sort=[("created_at", 1)]
        )
        
        title = "New Chat"
        if first_msg and first_msg.get("message"):
            msg_text = first_msg["message"]
            # Truncate to 30 chars for sidebar display
            title = msg_text[:30] + ("…" if len(msg_text) > 30 else "")
        
        result.append({
            "chat_id":    chat["chat_id"],
            "chat_title": title,
            "created_at": chat.get("created_at", "").isoformat()
                          if hasattr(chat.get("created_at"), "isoformat")
                          else str(chat.get("created_at", "")),
        })
    
    logger.info(f"the list of all the chats")
    return result


# all msg
@app.get("/{chat_id}")
async def get_messages(chat_id: str, user=Depends(get_current_user)):

    db = await get_database()

    msgs = db.chat_messages.find(
        {
            "chat_id": chat_id,
            "user_id": user["user_id"]
        }
    ).sort("created_at", 1)

    msgs = await msgs.to_list(length=50)

    logger.info(f"Found {len(msgs)} messages for chat {chat_id}")

    return {
        "message": [
            {
                "role": m["role"],
                "message": m["message"],
                "crisis_detected": m.get("crisis_detected", False)
            }
            for m in msgs
        ]
    }
    
    
# chat msg
@app.post("/{chat_id}")
async def chats(
    chat_id: str,
    request: ChatMessage,
    user = Depends(get_current_user)
):
    
    user_id = user['user_id']
    logger.info(f"Received message for chat {chat_id}")
    
    response = await chat_with_bot(
        user_id=user_id, 
        chat_id=chat_id,
        user_input=request.message
    )
    
    logger.info(f"Response generated by assistant {response}")
    return response
    
    

# clear chat
@app.delete("/{chat_id}/clear")
async def clear_chat(chat_id: str, user = Depends(get_current_user)):
    memory = MemoryHistory(chat_id)
    await memory.clear()
    
    return {"message": f"Chat {chat_id} cleared"}


@app.delete("/{chat_id}")
async def delete_chat(chat_id: str, user=Depends(get_current_user)):
    db = await get_database()
    
    await db.chats.delete_one({"chat_id": chat_id, "user_id": user["user_id"]})
    await db.chat_messages.delete_many({"chat_id": chat_id, "user_id": user["user_id"]})
    
    logger.info(f"Deleted chat {chat_id}")
    return {"message": f"Chat {chat_id} deleted"}